services:
  backend:
    tty: true
    restart: always
    build: ./backend
    image: "fastapi-demo-backend:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
      - ./files:/app/files
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    env_file: 
      - ./backend/.env
    ports:
      - 8000:8000
    depends_on:
      - database
      - redis
    networks:
      - default

  database:
    image: postgres:latest
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ./backend/.env
    ports:
      - 333:80
    depends_on:
      - database
    networks:
      - default
    volumes:
      - ./configs/pgadmin-servers.json:/pgadmin4/servers.json:ro

  redis:
    restart: always
    image: redis:alpine
    logging:
      driver: "local"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - default
    
  celery_worker:
    build: ./backend
    image: "fastapi-demo-backend:latest"
    entrypoint: ["./entrypoints/celery_worker.sh"]
    volumes:
      - ./files:/app/files
    depends_on:
      - backend
      - redis
    logging:
      driver: "local"
      options:
        max-size: "200k"
        max-file: "10"
    deploy:
      resources:
        limits:
          cpus: '0.50'
    networks:
      - default

  flower:
    build: ./backend
    image: "fastapi-demo-backend:latest"
    entrypoint: ["./entrypoints/flower.sh"]
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery_worker
    env_file:
      - ./backend/.env
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: