services:
  # Main reverse proxy - routes all traffic
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - default

  # Frontend React application
  frontend:
    build:
      context: ./frontend/demo-app
      dockerfile: Dockerfile.dev  # Use dev dockerfile for hot reload
    image: "fastapi-demo-frontend:dev"
    restart: always
    volumes:
      - ./frontend/demo-app:/app  # Mount source code for hot reload
      - /app/node_modules  # Persist node_modules in container
    environment:
      - VITE_API_BASE_URL=http://localhost/api/v1
      - CHOKIDAR_USEPOLLING=true  # Enable file watching in Docker
    ports:
      - 3000:3000  # Expose Vite dev server directly
    depends_on:
      - backend
    networks:
      - default

  backend:
    tty: true
    restart: always
    build: ./backend
    image: "fastapi-demo-backend:latest"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./backend:/app
      - ./files:/app/files
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    env_file:
      - ./backend/.env
    ports:
      - 8000:8000  # Direct access for development/debugging
    depends_on:
      - database
      - redis
    networks:
      - default

  database:
    image: postgres:latest
    env_file: ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - 5432:5432
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4:latest
    env_file: ./backend/.env
    ports:
      - 333:80
    depends_on:
      - database
    networks:
      - default
    volumes:
      - ./configs/pgadmin-servers.json:/pgadmin4/servers.json:ro

  redis:
    restart: always
    image: redis:alpine
    networks:
      - default

  celery_worker:
    image: "fastapi-demo-backend:latest"
    entrypoint: ["./entrypoints/celery_worker.sh"]
    volumes:
      - ./files:/app/files
    depends_on:
      - backend
      - redis
    networks:
      - default

  flower:
    image: "fastapi-demo-backend:latest"
    entrypoint: ["./entrypoints/flower.sh"]
    ports:
      - 5555:5555
    depends_on:
      - redis
      - celery_worker
    env_file:
      - ./backend/.env
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data: