"""tables_creation_

Revision ID: c0bcc1ea7a9f
Revises:
Create Date: 2025-05-23 15:07:36.709748

"""

from alembic import op
import sqlalchemy as sa
from app.database.models.orders.enums.OrderServiceType import OrderServiceType

# revision identifiers, used by Alembic.
revision = "c0bcc1ea7a9f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drivers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("phone", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_drivers_id"), "drivers", ["id"], unique=False)
    op.create_table(
        "terminals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_terminals_id"), "terminals", ["id"], unique=False)
    op.create_table(
        "trailers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("license_plate", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trailers_id"), "trailers", ["id"], unique=False)
    op.create_table(
        "trucks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=False),
        sa.Column("license_plate", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trucks_id"), "trucks", ["id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("reference", sa.String(length=32), nullable=True),
        sa.Column("service", OrderServiceType(), nullable=True),
        sa.Column("eta_date", sa.Date(), nullable=True),
        sa.Column("eta_time", sa.Time(), nullable=True),
        sa.Column("etd_date", sa.Date(), nullable=True),
        sa.Column("etd_time", sa.Time(), nullable=True),
        sa.Column("commodity", sa.String(length=256), nullable=True),
        sa.Column("pallets", sa.Integer(), nullable=True),
        sa.Column("boxes", sa.Integer(), nullable=True),
        sa.Column("kilos", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(length=1024), nullable=True),
        sa.Column("priority", sa.Boolean(), nullable=True),
        sa.Column("terminal_id", sa.UUID(), nullable=True),
        sa.Column(
            "created_at", sa.Date(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column(
            "updated_at", sa.Date(), server_default=sa.text("now()"), nullable=True
        ),
        sa.Column("eta_driver_id", sa.UUID(), nullable=True),
        sa.Column("eta_trailer_id", sa.UUID(), nullable=True),
        sa.Column("eta_truck_id", sa.UUID(), nullable=True),
        sa.Column("eta_driver", sa.String(length=256), nullable=True),
        sa.Column("eta_driver_phone", sa.String(length=32), nullable=True),
        sa.Column("eta_truck", sa.String(length=256), nullable=True),
        sa.Column("eta_trailer", sa.String(length=256), nullable=True),
        sa.Column("etd_driver_id", sa.UUID(), nullable=True),
        sa.Column("etd_trailer_id", sa.UUID(), nullable=True),
        sa.Column("etd_truck_id", sa.UUID(), nullable=True),
        sa.Column("etd_driver", sa.String(length=256), nullable=True),
        sa.Column("etd_driver_phone", sa.String(length=32), nullable=True),
        sa.Column("etd_truck", sa.String(length=256), nullable=True),
        sa.Column("etd_trailer", sa.String(length=256), nullable=True),
        sa.ForeignKeyConstraint(
            ["eta_driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["eta_trailer_id"],
            ["trailers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["eta_truck_id"],
            ["trucks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["etd_driver_id"],
            ["drivers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["etd_trailer_id"],
            ["trailers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["etd_truck_id"],
            ["trucks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["terminal_id"],
            ["terminals.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_trucks_id"), table_name="trucks")
    op.drop_table("trucks")
    op.drop_index(op.f("ix_trailers_id"), table_name="trailers")
    op.drop_table("trailers")
    op.drop_index(op.f("ix_terminals_id"), table_name="terminals")
    op.drop_table("terminals")
    op.drop_index(op.f("ix_drivers_id"), table_name="drivers")
    op.drop_table("drivers")
    # ### end Alembic commands ###
